### ISSUE TITLE
eHDSI value sets not found

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/mpd#20]
Some example bindings use eHDSI value sets, but they are not found even when built with HL7-EU tx. 
Is it possible to use them as a package in case tx fix takes longer?

**Comment by costateixeira** [comment]
this is now fixed from the HL7 tooling perspective. The only issue seems to be the redirect to https which I have to find if it is in the browser. Anyway seems a good excuse to add https to the tx server

**Comment by rlindstrm** [comment]
Local build with HL7-EU tx still cannot find the value sets.

**Comment by rlindstrm** [comment]
This is now fully fixed. Works with autobuild, too.
